markdown: rdiscount
auto: true
url: http://bbaget.com
exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test", "templates"]
keywords: france, tourism in france, dordogne, rentals, villas, cottages, apple, steve jobs, technology, holiday in france, villa in france, perigord, perigord noir, books, yoga, health, food, natural food, paleo

owner-name: Grant Neale
owner-page: http://bbaget.com
owner-email: gneale@mac.com
owner-site: Bbaget


license: All rights reserved

pygments: true
permalink: /:year/:month/:day/:title
regeneration: true
lsi: true
exclude: README.textile Rakefile
tag_title_prefix: 'Tag: '
base_url: http://bbaget.com
title: Bbaget - France and other stuff
# post_types:
#   - portfolio
#   - gallery